apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: developer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp
  template:
    metadata:
      labels:
        app: emp
    spec:
      containers:
        - name: emp
          image: observabilityacr9425.azurecr.io/empdemo:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
      imagePullSecrets:
        - name: acr-secret
              
      
